theme: jekyll-theme-cayman
title: HaSa's Blog
description: I'm a student from Germany. As one of my hobbies is programming it feels natural to write a little about.
permalink: /blog/:year/:month/:day/:title/
